package es.cd40;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-10T15:05:38.561+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://CD40.es/", name = "InterfazSOAPConfiguracionHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InterfazSOAPConfiguracionHttpPost {

    /**
     * Pasándole el identificador de usuario y el sistema al que pertenece, devuelve la lista de enlaces externos del usuario.
     */
    @WebMethod(operationName = "GetListaEnlacesExternos")
    @WebResult(name = "ArrayOfCfgEnlaceExterno", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfCfgEnlaceExterno getListaEnlacesExternos(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema,
        @WebParam(partName = "id_usuario", name = "id_usuario", targetNamespace = "http://CD40.es/")
        java.lang.String idUsuario
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de troncales.
     */
    @WebMethod(operationName = "GetPlanTroncales")
    @WebResult(name = "ArrayOfListaTroncales", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfListaTroncales getPlanTroncales(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador del sistema, proporciona la dirección multicast y el puerto para notificación de una activación de configuración.
     */
    @WebMethod(operationName = "GetParametrosMulticast")
    @WebResult(name = "ParametrosMulticast", targetNamespace = "http://CD40.es/", partName = "Body")
    public ParametrosMulticast getParametrosMulticast(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de numeración ATS.
     */
    @WebMethod(operationName = "GetPlanNumeracionATS")
    @WebResult(name = "ArrayOfNumeracionATS", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfNumeracionATS getPlanNumeracionATS(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador hardware del terminal de voz y el sistema al que pertenece, devuelve el identificador de usuario alojado en el mismo y el modo de arranque ('A' o 'M').
     */
    @WebMethod(operationName = "LoginTop")
    @WebResult(name = "LoginTerminalVoz", targetNamespace = "http://CD40.es/", partName = "Body")
    public LoginTerminalVoz loginTop(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema,
        @WebParam(partName = "id_hw", name = "id_hw", targetNamespace = "http://CD40.es/")
        java.lang.String idHw
    );

    /**
     * Pasándole el identificador del sistema devuelve los parámetros generales del sistema.
     */
    @WebMethod(operationName = "GetParametrosGenerales")
    @WebResult(name = "ParametrosGeneralesSistema", targetNamespace = "http://CD40.es/", partName = "Body")
    public ParametrosGeneralesSistema getParametrosGenerales(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador hardware de la pasarela y el sistema al que pertenece, devuelve la configuración de la pasarela.
     */
    @WebMethod(operationName = "GetCfgPasarela")
    @WebResult(name = "CfgPasarela", targetNamespace = "http://CD40.es/", partName = "Body")
    public CfgPasarela getCfgPasarela(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema,
        @WebParam(partName = "id_hw", name = "id_hw", targetNamespace = "http://CD40.es/")
        java.lang.String idHw
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de asignación de usuarios a terminales de voz.
     */
    @WebMethod(operationName = "GetPlanAsignacionUsuarios")
    @WebResult(name = "ArrayOfAsignacionUsuariosTV", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfAsignacionUsuariosTV getPlanAsignacionUsuarios(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador de usuario y el sistema al que pertenece, devuelve la lista de enlaces internos del usuario.
     */
    @WebMethod(operationName = "GetListaEnlacesInternos")
    @WebResult(name = "ArrayOfCfgEnlaceInterno", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfCfgEnlaceInterno getListaEnlacesInternos(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema,
        @WebParam(partName = "id_usuario", name = "id_usuario", targetNamespace = "http://CD40.es/")
        java.lang.String idUsuario
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de redes.
     */
    @WebMethod(operationName = "GetPlanRedes")
    @WebResult(name = "ArrayOfListaRedes", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfListaRedes getPlanRedes(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador del sistema devuelve el conjunto de parámetros que conforman la configuración común de los distintos elementos del SCV.
     */
    @WebMethod(operationName = "GetConfigSistema")
    @WebResult(name = "ConfiguracionSistema", targetNamespace = "http://CD40.es/", partName = "Body")
    public ConfiguracionSistema getConfigSistema(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Configuración relativa a los equipos N+M
     */
    @WebMethod(operationName = "GetPoolNMElements")
    @WebResult(name = "ArrayOfNode", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfNode getPoolNMElements(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole un identificador de sistema, un identificador de recurso y el tipo de interfaz (TI_Radio=0, TI_LCEN=1, TI_BC=2, TI_BL=3, TI_AB=4, TI_ATS_R2=5, TI_ATS_N5=6, TI_ATS_QSIG=7, TI_ISDN_2BD=8, TI_ISDN_30BD=9, TI_I_O=10, TI_DATOS=11), retorna los parámetros correspondientes al recurso.
     */
    @WebMethod(operationName = "GetParametrosRecursoById")
    @WebResult(name = "Tablas", targetNamespace = "http://CD40.es/", partName = "Body")
    public Tablas getParametrosRecursoById(
        @WebParam(partName = "idSistema", name = "idSistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema,
        @WebParam(partName = "idRecurso", name = "idRecurso", targetNamespace = "http://CD40.es/")
        java.lang.String idRecurso,
        @WebParam(partName = "tipo", name = "tipo", targetNamespace = "http://CD40.es/")
        java.lang.String tipo
    );

    /**
     * Pasándole el identificador de usuario y el sistema al que pertenece, devuelve la configuración del usuario.
     */
    @WebMethod(operationName = "GetCfgUsuario")
    @WebResult(name = "CfgUsuario", targetNamespace = "http://CD40.es/", partName = "Body")
    public CfgUsuario getCfgUsuario(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema,
        @WebParam(partName = "id_usuario", name = "id_usuario", targetNamespace = "http://CD40.es/")
        java.lang.String idUsuario
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de direccionamiento IP.
     */
    @WebMethod(operationName = "GetPlanDireccionamientoIP")
    @WebResult(name = "ArrayOfDireccionamientoIP", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfDireccionamientoIP getPlanDireccionamientoIP(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador de sistema, devuelve la versión de la configuración activa registrada en la base de datos
     */
    @WebMethod(operationName = "GetVersionConfiguracion_XML")
    public void getVersionConfiguracionXML(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Envia el estado de los nodos que componen el cluster
     */
    @WebMethod(operationName = "GetEstadoCluster")
    @WebResult(name = "EstadoCluster", targetNamespace = "http://CD40.es/", partName = "Body")
    public EstadoCluster getEstadoCluster();

    /**
     * Configuración relativa a frecuencias HF Ulises5Ki.
     */
    @WebMethod(operationName = "GetPoolHfElement")
    @WebResult(name = "ArrayOfPoolHfElement", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfPoolHfElement getPoolHfElement(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de asignación de recursos a pasarelas.
     */
    @WebMethod(operationName = "GetPlanAsignacionRecursos")
    @WebResult(name = "ArrayOfAsignacionRecursosGW", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfAsignacionRecursosGW getPlanAsignacionRecursos(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador de sistema, devuelve la versión de la configuración activa registrada en la base de datos
     */
    @WebMethod(operationName = "GetVersionConfiguracion")
    @WebResult(name = "string", targetNamespace = "http://CD40.es/", partName = "Body")
    public java.lang.String getVersionConfiguracion(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador del sistema devuelve el plan de direccionamiento SIP.
     */
    @WebMethod(operationName = "GetPlanDireccionamientoSIP")
    @WebResult(name = "ArrayOfDireccionamientoSIP", targetNamespace = "http://CD40.es/", partName = "Body")
    public ArrayOfDireccionamientoSIP getPlanDireccionamientoSIP(
        @WebParam(partName = "id_sistema", name = "id_sistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );

    /**
     * Pasándole el identificador de sistema, devuelve el Scv [1|2] activo. 0 si error
     */
    @WebMethod(operationName = "GetScvActivo")
    @WebResult(name = "string", targetNamespace = "http://CD40.es/", partName = "Body")
    public java.lang.String getScvActivo(
        @WebParam(partName = "idSistema", name = "idSistema", targetNamespace = "http://CD40.es/")
        java.lang.String idSistema
    );
}
