//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ObjectBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.ObjectBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object builder has no strategies..
        /// </summary>
        internal static string BuilderHasNoStrategies {
            get {
                return ResourceManager.GetString("BuilderHasNoStrategies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] {1} / {2} :: {3}.
        /// </summary>
        internal static string BuilderStrategyTraceBuildUp {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceBuildUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [{0}] {1} :: {2}.
        /// </summary>
        internal static string BuilderStrategyTraceTearDown {
            get {
                return ResourceManager.GetString("BuilderStrategyTraceTearDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [BuilderBase] Finished BuildUp on {0} with ID {1}.
        /// </summary>
        internal static string BuildUpFinished {
            get {
                return ResourceManager.GetString("BuildUpFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [BuilderBase] Starting BuildUp on {0} with ID {1}.
        /// </summary>
        internal static string BuildUpStarting {
            get {
                return ResourceManager.GetString("BuildUpStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calling constructor({0}).
        /// </summary>
        internal static string CallingConstructor {
            get {
                return ResourceManager.GetString("CallingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calling method {0}({1}).
        /// </summary>
        internal static string CallingMethod {
            get {
                return ResourceManager.GetString("CallingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calling IBuilderAware.OnBuiltUp().
        /// </summary>
        internal static string CallingOnBuiltUp {
            get {
                return ResourceManager.GetString("CallingOnBuiltUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calling IBuilderAware.OnTearingDown().
        /// </summary>
        internal static string CallingOnTearingDown {
            get {
                return ResourceManager.GetString("CallingOnTearingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting property {0}({1}).
        /// </summary>
        internal static string CallingProperty {
            get {
                return ResourceManager.GetString("CallingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not create an instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotCreateInstanceOfType {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In class &apos;{0}&apos;, cannot inject value on property &apos;{1}&apos; because it is read-only..
        /// </summary>
        internal static string CannotInjectReadOnlyProperty {
            get {
                return ResourceManager.GetString("CannotInjectReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not locate dependency &quot;{0}&quot;..
        /// </summary>
        internal static string DependencyMissing {
            get {
                return ResourceManager.GetString("DependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Too many dependency injection attributes defined on {0}.{1}..
        /// </summary>
        internal static string InvalidAttributeCombination {
            get {
                return ResourceManager.GetString("InvalidAttributeCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid enumeration value..
        /// </summary>
        internal static string InvalidEnumerationValue {
            get {
                return ResourceManager.GetString("InvalidEnumerationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An item with the given key is already present in the dictionary..
        /// </summary>
        internal static string KeyAlreadyPresentInDictionary {
            get {
                return ResourceManager.GetString("KeyAlreadyPresentInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing policy to build {0} named &apos;{1}&apos;..
        /// </summary>
        internal static string MissingPolicyNamed {
            get {
                return ResourceManager.GetString("MissingPolicyNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing policy to build unnamed {0}..
        /// </summary>
        internal static string MissingPolicyUnnamed {
            get {
                return ResourceManager.GetString("MissingPolicyUnnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find an appropriately matching constructor..
        /// </summary>
        internal static string NoAppropriateConstructor {
            get {
                return ResourceManager.GetString("NoAppropriateConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered as singleton.
        /// </summary>
        internal static string SingletonRegistered {
            get {
                return ResourceManager.GetString("SingletonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Returning existing singleton.
        /// </summary>
        internal static string SingletonReturned {
            get {
                return ResourceManager.GetString("SingletonReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [BuilderBase] Finished TearDown on {0}.
        /// </summary>
        internal static string TearDownFinished {
            get {
                return ResourceManager.GetString("TearDownFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [BuilderBase] Starting TearDown on {0}.
        /// </summary>
        internal static string TearDownStarting {
            get {
                return ResourceManager.GetString("TearDownStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapped to {0} / {1}.
        /// </summary>
        internal static string TypeMapped {
            get {
                return ResourceManager.GetString("TypeMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a While resolving dependencies for {2}, the provided type {1} is not compatible with {0}..
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
    }
}
