//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u5ki.RemoteControlService.OIDs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sirtap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sirtap() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("u5ki.RemoteControlService.OIDs.Sirtap", typeof(Sirtap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.6.0.
        /// </summary>
        public static string CarrierOffStatus {
            get {
                return ResourceManager.GetString("CarrierOffStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.23.0.
        /// </summary>
        public static string ChannelSpacing {
            get {
                return ResourceManager.GetString("ChannelSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.2.0.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.4.9.
        /// </summary>
        public static string eraseKeys {
            get {
                return ResourceManager.GetString("eraseKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.4.0.
        /// </summary>
        public static string Frecuency {
            get {
                return ResourceManager.GetString("Frecuency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.2.2.3.1.
        /// </summary>
        public static string frequencyCh1 {
            get {
                return ResourceManager.GetString("frequencyCh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.2.3.3.1.
        /// </summary>
        public static string frequencyCh2 {
            get {
                return ResourceManager.GetString("frequencyCh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.3.5.
        /// </summary>
        public static string GetChannels {
            get {
                return ResourceManager.GetString("GetChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.21.0.
        /// </summary>
        public static string InServiceMode {
            get {
                return ResourceManager.GetString("InServiceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.4.10.
        /// </summary>
        public static string loadKeys {
            get {
                return ResourceManager.GetString("loadKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.9.0.
        /// </summary>
        public static string Modulation {
            get {
                return ResourceManager.GetString("Modulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.1.2.3.1.0.
        /// </summary>
        public static string OperationalMode {
            get {
                return ResourceManager.GetString("OperationalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.6.1.1.6.0.
        /// </summary>
        public static string OperationalStatusATC {
            get {
                return ResourceManager.GetString("OperationalStatusATC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.2.2.3.2.
        /// </summary>
        public static string powerLevelCh1 {
            get {
                return ResourceManager.GetString("powerLevelCh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.2.3.3.2.
        /// </summary>
        public static string powerLevelCh2 {
            get {
                return ResourceManager.GetString("powerLevelCh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.4.4.4.4.4.0.
        /// </summary>
        public static string SetCryptKeys {
            get {
                return ResourceManager.GetString("SetCryptKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.4.14.
        /// </summary>
        public static string SetGetRadioChannel {
            get {
                return ResourceManager.GetString("SetGetRadioChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.50.2.
        /// </summary>
        public static string SetTxInhibit {
            get {
                return ResourceManager.GetString("SetTxInhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.1234.3.3.3.3.3.0.
        /// </summary>
        public static string SetVFallocSqh {
            get {
                return ResourceManager.GetString("SetVFallocSqh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.51.2.
        /// </summary>
        public static string WFCh1 {
            get {
                return ResourceManager.GetString("WFCh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.3.6.1.4.1.16215.1.18.1.52.2.
        /// </summary>
        public static string WFCh2 {
            get {
                return ResourceManager.GetString("WFCh2", resourceCulture);
            }
        }
    }
}
