#ifndef __AUDIO_H__
#define __AUDIO_H__

typedef enum 
{
	AC_NODEF = 0,
	AC_IT,
	AC_OT,
	AC_FEATURE,
	AC_MIXER,
	AC_SELECTOR
}AC_NODE_TYPE;

#define MAX_FEATURE_VOL_NUM		6

typedef enum
{
	FEATURE_DAC = 0,
	FEATURE_ADC_LINE,
	FEATURE_ADC_MIC,
	FEATURE_MIXER,
	FEATURE_MONITOR_LINE,
	FEATURE_MONITOR_MIC,
	FEATURE_SPDIF
}FEATURE_UNIT_NO;	

// Feature UNIT Control Selector
#define MUTE_CONTROL			0x01
#define VOLUME_CONTROL			0x02
#define BASS_CONTROL			0x03
#define TREBLE_CONTROL			0x05
#define AUTOMATIC_GAIN_CONTROL	0x07

// Endpoint Control Selector
#define SAMPLING_FREQ_CONTROL	0x01

// Audio Class-Specific Request Codes
typedef enum 
{
	CMD_NODEF = 0,
 	CMD_SET_CURRENT,
 	CMD_SET_MIN,
 	CMD_SET_MAX,
 	CMD_SET_RES,
 	CMD_GET_CURRENT = 0x81,
 	CMD_GET_MIN,
 	CMD_GET_MAX,
 	CMD_GET_RES,
 	CMD_GET_MEM = 0x85
}AC_CMD_ATTR;

typedef enum
{
	CTRL_SAMPLING_RATE_8000 = 0,
	CTRL_SAMPLING_RATE_11025,
	CTRL_SAMPLING_RATE_16000,
	CTRL_SAMPLING_RATE_22050,
	CTRL_SAMPLING_RATE_32000,
	CTRL_SAMPLING_RATE_44100,
	CTRL_SAMPLING_RATE_48000,
	CTRL_SAMPLING_RATE_88200,
	CTRL_SAMPLING_RATE_96000
}FIFO_SAMPLING_RATE_CTRL;	

#define CTRL_SPDIF_OUT_SAMPLING_RATE_22050	0x06
#define CTRL_SPDIF_OUT_SAMPLING_RATE_32000	0x02
#define CTRL_SPDIF_OUT_SAMPLING_RATE_44100	0x04
#define CTRL_SPDIF_OUT_SAMPLING_RATE_48000	0x00
#define CTRL_SPDIF_OUT_SAMPLING_RATE_88200	0x05
#define CTRL_SPDIF_OUT_SAMPLING_RATE_96000	0x01
#define CTRL_SPDIF_OUT_SAMPLING_RATE_192000	0x03	
#define CTRL_SPDIF_OUT_SAMPLING_RATE_NONE	0xFF

#define EQ_COEFF_TABLE0	0x0000
#define EQ_COEFF_TABLE1	0x0080
#define EQ_COEFF_TABLE2	0x0100
#define EQ_COEFF_TABLE3	0x0180
#define EQ_MODE_0	0x00
#define EQ_MODE_1	0x01
#define EQ_MODE_2	0x02
#define EQ_MODE_3	0x03

typedef enum
{
	SELECTOR_MIC = 1,
	SELECTOR_LINE_IN,
	SELECTOR_SPDIF_IN,
	SELECTOR_SMIX_IN
}SELECTOR_SELECT;	

#define SAMPLING_RATE_NUM		9

#endif // __AUDIO_H__